name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.21
        id: go

      - name: Check Code
        uses: actions/checkout@v4

      - name: Test
        run: |
          make test
